### PR TITLE
Move Style/EmptyLineAfterGuardClause cop to Layout department

### PR DESCRIPTION
**Pull request by mkmn**
see: https://github.com/rubocop-hq/rubocop/pull/5886

```
Style/EmptyLineAfterGuardClause has the wrong namespace - should be Layout
```

### CODE REVIEW

**Comment by onk** [comment]
FYI: #56 

I have not seen the changes of v0.53...v0.56.
How is your impression of using it in your project?

**Comment by koic** [comment]
Layout/EmptyLineAfterGuardClause cop will be enabled by default at the next release of RuboCop (maybe 0.59.0) .
rubocop-hq/rubocop#6235

**Comment by libra189** [comment]
Hello
A new version of RuboCop has been released at 0.59.2.
[rubocop-hq/rubocop#6235](https://github.com/rubocop-hq/rubocop/pull/6235) has been merged in this version.
Do you plan to make changes in this project?

I'm sorry for my bad English
Have a good day.

**Comment by SpringMT** [comment]
How about this PR?

**Comment by onk** [comment]
In rubocop v0.59.0, Layout/EmptyLineAfterGuardClause is enabled by default.
So remove the configuration. #58

**Comment by onk** [comment]
Released no warning version as v0.53.0.2.
Have you solved the problem with this?

**Comment by libra189** [comment]
> In rubocop v0.59.0, Layout/EmptyLineAfterGuardClause is enabled by default.
> So remove the configuration. #58

Thanks.
I was solve the trouble.
Please close this PR at #57.

**Pull request closed without merging**
